In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('https://courses.edx.org/c4x/MITx/15.071x_2/asset/WHO.csv')

In [3]:
df.head()

,Country,Region,Population,Under15,Over60,FertilityRate,LifeExpectancy,ChildMortality,CellularSubscribers,LiteracyRate,GNI,PrimarySchoolEnrollmentMale,PrimarySchoolEnrollmentFemale
0,Afghanistan,Eastern Mediterranean,29825,47.42,3.82,5.40,60,98.5,54.26,NaN,1140.0,NaN,NaN
1,Albania,Europe,3162,21.33,14.93,1.75,74,16.7,96.39,NaN,8820.0,NaN,NaN
2,Algeria,Africa,38482,27.42,7.17,2.83,73,20.0,98.99,NaN,8310.0,98.2,96.4
3,Andorra,Europe,78,15.20,22.86,NaN,82,3.2,75.49,NaN,NaN,78.4,79.4
4,Angola,Africa,20821,47.58,3.84,6.10,51,163.5,48.38,70.1,5230.0,93.1,78.2

In [4]:
df.describe()

,Population,Under15,Over60,FertilityRate,LifeExpectancy,ChildMortality,CellularSubscribers,LiteracyRate,GNI,PrimarySchoolEnrollmentMale,PrimarySchoolEnrollmentFemale
count,1.940000e+02,194.000000,194.000000,183.000000,194.000000,194.000000,184.000000,103.000000,162.000000,101.000000,101.000000
mean,3.635997e+04,28.732423,11.163660,2.940656,70.010309,36.148969,93.641522,83.710680,13320.925926,90.850495,89.632673
std,1.379031e+05,10.534573,7.149331,1.480984,9.259075,37.992935,41.400447,17.530645,15192.988650,11.017147,12.817614
min,1.000000e+00,13.120000,0.810000,1.260000,47.000000,2.200000,2.570000,31.100000,340.000000,37.200000,32.500000
25%,1.695750e+03,18.717500,5.200000,1.835000,64.000000,8.425000,63.567500,71.600000,2335.000000,87.700000,87.300000
50%,7.790000e+03,28.650000,8.530000,2.400000,72.500000,18.600000,97.745000,91.800000,7870.000000,94.700000,95.100000
75%,2.453525e+04,37.752500,16.687500,3.905000,76.000000,55.975000,120.805000,97.850000,17557.500000,98.100000,97.900000
max,1.390000e+06,49.990000,31.920000,7.580000,83.000000,181.600000,196.410000,99.800000,86440.000000,100.000000,100.000000

In [13]:
# Mean of over60 population
df.Over60.mean()

11.163659793814434

In [14]:
# Country has the smallest percentage of the population over 60?
index_small60 = df.Over60.idxmin()
df.iloc[index_small60]['Country']

'United Arab Emirates'

In [15]:
# Country has the smallest percentage of the population over 60?
index_highLR = df.LiteracyRate.idxmax()
df.iloc[index_highLR]['Country']

'Cuba'

In [17]:
df.head()

,Country,Region,Population,Under15,Over60,FertilityRate,LifeExpectancy,ChildMortality,CellularSubscribers,LiteracyRate,GNI,PrimarySchoolEnrollmentMale,PrimarySchoolEnrollmentFemale
0,Afghanistan,Eastern Mediterranean,29825,47.42,3.82,5.40,60,98.5,54.26,NaN,1140.0,NaN,NaN
1,Albania,Europe,3162,21.33,14.93,1.75,74,16.7,96.39,NaN,8820.0,NaN,NaN
2,Algeria,Africa,38482,27.42,7.17,2.83,73,20.0,98.99,NaN,8310.0,98.2,96.4
3,Andorra,Europe,78,15.20,22.86,NaN,82,3.2,75.49,NaN,NaN,78.4,79.4
4,Angola,Africa,20821,47.58,3.84,6.10,51,163.5,48.38,70.1,5230.0,93.1,78.2

In [22]:
#Region with min mean Child Mortality?
groupeddd = df.groupby(['Region', 'Country']).sum()
grouped

                                                  Population  Under15  Over60  \
Region          Country
Africa          Algeria                                38482    27.42    7.17
                Angola                                 20821    47.58    3.84
                Benin                                  10051    42.95    4.54
                Botswana                                2004    33.75    5.63
                Burkina Faso                           16460    45.66    3.88
                Burundi                                 9850    44.20    3.87
                Cameroon                               21700    43.08    4.89
                Cape Verde                               494    30.17    7.05
                Central African Republic                4525    40.07    5.74
                Chad                                   12448    48.52    3.80
                Comoros                                  718    42.17    4.50
                Congo                                   4337    42.37    5.13
                Democratic Republic of the Congo       65705    45.11    4.51
                Equatorial Guinea                        736    38.95    4.53
                Eritrea                                 6131    43.10    3.73
                Ethiopia                               91729    43.29    5.17
                Gabon                                   1633    38.49    7.38
                Gambia                                  1791    45.90    3.72
                Ghana                                  25366    38.59    5.40
                Guinea                                 11451    42.46    5.03
                Guinea-Bissau                           1664    41.55    5.06
                Ivory Coast                            19840    41.48    5.10
                Kenya                                  43178    42.37    4.25
                Lesotho                                 2052    36.75    6.31
                Liberia                                 4190    43.06    4.76
                Madagascar                             22294    42.72    4.45
                Malawi                                 15906    45.44    4.92
                Mali                                   14854    47.14    4.29
                Mauritania                              3796    40.22    4.94
                Mauritius                               1240    20.17   13.23
...                                                      ...      ...     ...
South-East Asia Sri Lanka                              21098    25.15   12.40
                Thailand                               66785    18.47   13.96
                Timor-Leste                             1114    46.33    5.16
Western Pacific Australia                              23050    18.95   19.46
                Brunei Darussalam                        412    25.75    7.03
                Cambodia                               14865    31.23    7.67
                China                                1390000    17.95   13.42
                Cook Islands                              21    30.61    9.07
                Fiji                                     875    28.88    8.38
                Japan                                 127000    13.12   31.92
                Kiribati                                 101    30.10    8.84
                Lao People's Democratic Republic        6646    35.61    5.76
                Malaysia                               29240    26.65    8.21
                Marshall Islands                          53    30.10    8.84
                Micronesia (Federated States of)         103    35.81    6.67
                Mongolia                                2796    27.05    5.80
                Nauru                                     10    30.10    8.84
                New Zealand                             4460    20.26   19.01
                Niue                                       1    30.61    9.07
                Palau                                     21    30.10    8.84
                Papua New Guinea                        7167    38.37    4.79
                Philippines                            96707    34.53    6.21
                Republic of Korea                      49003    15.25   16.58
                Samoa                                    189    37.88    7.39
                Singapore                               5303    16.48   15.13
                Solomon Islands                          550    40.37    5.10
                Tonga                                    105    37.33    7.96
                Tuvalu                                    10    30.61    9.07
                Vanuatu                                  247    37.37    6.02
                Viet Nam                               90796    22.87    9.32

                                                  FertilityRate  \
Region          Country
Africa          Algeria                                    2.83
                Angola                                     6.10
                Benin                                      5.01
                Botswana                                   2.71
                Burkina Faso                               5.78
                Burundi                                    6.21
                Cameroon                                   4.94
                Cape Verde                                 2.38
                Central African Republic                   4.54
                Chad                                       6.49
                Comoros                                    4.85
                Congo                                      5.05
                Democratic Republic of the Congo           6.15
                Equatorial Guinea                          5.04
                Eritrea                                    4.88
                Ethiopia                                   4.77
                Gabon                                      4.18
                Gambia                                     5.79
                Ghana                                      3.99
                Guinea                                     5.09
                Guinea-Bissau                              5.05
                Ivory Coast                                4.91
                Kenya                                      4.54
                Lesotho                                    3.15
                Liberia                                    4.95
                Madagascar                                 4.59
                Malawi                                     5.55
                Mali                                       6.85
                Mauritania                                 4.78
                Mauritius                                  1.51
...                                                         ...
South-East Asia Sri Lanka                                  2.35
                Thailand                                   1.43
                Timor-Leste                                6.11
Western Pacific Australia                                  1.89
                Brunei Darussalam                          2.03
                Cambodia                                   2.93
                China                                      1.66
                Cook Islands                               0.00
                Fiji                                       2.64
                Japan                                      1.39
                Kiribati                                   3.01
                Lao People's Democratic Republic           3.20
                Malaysia                                   1.99
                Marshall Islands                           0.00
                Micronesia (Federated States of)           3.40
                Mongolia                                   2.45
                Nauru                                      0.00
                New Zealand                                2.10
                Niue                                       0.00
                Palau                                      0.00
                Papua New Guinea                           3.90
                Philippines                                3.11
                Republic of Korea                          1.29
                Samoa                                      4.28
                Singapore                                  1.27
                Solomon Islands                            4.17
                Tonga                                      3.86
                Tuvalu                                     0.00
                Vanuatu                                    3.46
                Viet Nam                                   1.79

                                                  LifeExpectancy  \
Region          Country
Africa          Algeria                                       73
                Angola                                        51
                Benin                                         57
                Botswana                                      66
                Burkina Faso                                  56
                Burundi                                       53
                Cameroon                                      53
                Cape Verde                                    72
                Central African Republic                      48
                Chad                                          51
                Comoros                                       62
                Congo                                         58
                Democratic Republic of the Congo              49
                Equatorial Guinea                             54
                Eritrea                                       61
                Ethiopia                                      60
                Gabon                                         62
                Gambia                                        58
                Ghana                                         64
                Guinea                                        55
                Guinea-Bissau                                 50
                Ivory Coast                                   56
                Kenya                                         60
                Lesotho                                       50
                Liberia                                       59
                Madagascar                                    66
                Malawi                                        58
                Mali                                          51
                Mauritania                                    59
                Mauritius                                     74
...                                                          ...
South-East Asia Sri Lanka                                     75
                Thailand                                      74
                Timor-Leste                                   64
Western Pacific Australia                                     82
                Brunei Darussalam                             77
                Cambodia                                      65
                China                                         76
                Cook Islands                                  77
                Fiji                                          70
                Japan                                         83
                Kiribati                                      67
                Lao People's Democratic Republic              68
                Malaysia                                      74
                Marshall Islands                              60
                Micronesia (Federated States of)              69
                Mongolia                                      68
                Nauru                                         71
                New Zealand                                   81
                Niue                                          72
                Palau                                         72
                Papua New Guinea                              63
                Philippines                                   69
                Republic of Korea                             81
                Samoa                                         73
                Singapore                                     82
                Solomon Islands                               70
                Tonga                                         72
                Tuvalu                                        64
                Vanuatu                                       72
                Viet Nam                                      75

                                                  ChildMortality  \
Region          Country
Africa          Algeria                                     20.0
                Angola                                     163.5
                Benin                                       89.5
                Botswana                                    53.3
                Burkina Faso                               102.4
                Burundi                                    104.3
                Cameroon                                    94.9
                Cape Verde                                  22.2
                Central African Republic                   128.6
                Chad                                       149.8
                Comoros                                     77.6
                Congo                                       96.0
                Democratic Republic of the Congo           145.7
                Equatorial Guinea                          100.3
                Eritrea                                     51.8
                Ethiopia                                    68.3
                Gabon                                       62.0
                Gambia                                      72.9
                Ghana                                       72.0
                Guinea                                     101.2
                Guinea-Bissau                              129.1
                Ivory Coast                                107.6
                Kenya                                       72.9
                Lesotho                                     99.6
                Liberia                                     74.8
                Madagascar                                  58.2
                Malawi                                      71.0
                Mali                                       128.0
                Mauritania                                  84.0
                Mauritius                                   15.1
...                                                          ...
South-East Asia Sri Lanka                                    9.6
                Thailand                                    13.2
                Timor-Leste                                 56.7
Western Pacific Australia                                    4.9
                Brunei Darussalam                            8.0
                Cambodia                                    39.7
                China                                       14.0
                Cook Islands                                10.6
                Fiji                                        22.4
                Japan                                        3.0
                Kiribati                                    59.9
                Lao People's Democratic Republic            71.8
                Malaysia                                     8.5
                Marshall Islands                            37.9
                Micronesia (Federated States of)            38.5
                Mongolia                                    27.5
                Nauru                                       37.1
                New Zealand                                  5.7
                Niue                                        25.1
                Palau                                       20.8
                Papua New Guinea                            63.0
                Philippines                                 29.8
                Republic of Korea                            3.8
                Samoa                                       17.8
                Singapore                                    2.9
                Solomon Islands                             31.1
                Tonga                                       12.8
                Tuvalu                                      29.7
                Vanuatu                                     17.9
                Viet Nam                                    23.0

                                                  CellularSubscribers  \
Region          Country
Africa          Algeria                                         98.99
                Angola                                          48.38
                Benin                                           85.33
                Botswana                                       142.82
                Burkina Faso                                    45.27
                Burundi                                         22.33
                Cameroon                                        52.35
                Cape Verde                                      79.19
                Central African Republic                        40.65
                Chad                                            31.80
                Comoros                                         28.71
                Congo                                           93.84
                Democratic Republic of the Congo                23.09
                Equatorial Guinea                               59.15
                Eritrea                                          4.47
                Ethiopia                                        16.67
                Gabon                                          117.32
                Gambia                                          78.89
                Ghana                                           84.78
                Guinea                                          44.02
                Guinea-Bissau                                   56.18
                Ivory Coast                                     86.06
                Kenya                                           67.49
                Lesotho                                         56.17
                Liberia                                         49.17
                Madagascar                                      40.65
                Malawi                                          25.69
                Mali                                            68.32
                Mauritania                                      93.60
                Mauritius                                       99.04
...                                                               ...
South-East Asia Sri Lanka                                       87.05
                Thailand                                       111.63
                Timor-Leste                                     53.23
Western Pacific Australia                                      108.34
                Brunei Darussalam                              109.17
                Cambodia                                        96.17
                China                                           73.19
                Cook Islands                                     0.00
                Fiji                                            83.72
                Japan                                          104.95

In [23]:
means = grouped.mean(level=0, axis=0)
means

,Population,Under15,Over60,FertilityRate,LifeExpectancy,ChildMortality,CellularSubscribers,LiteracyRate,GNI,PrimarySchoolEnrollmentMale,PrimarySchoolEnrollmentFemale
Region,,,,,,,,,,,
Africa,19406.434783,40.937826,5.220652,4.724565,57.956522,84.036957,63.018043,54.071739,3935.869565,39.210870,37.113043
Americas,27364.828571,27.437429,10.943714,2.210571,74.342857,19.322857,103.962286,44.897143,10142.857143,55.877143,55.648571
Eastern Mediterranean,27827.863636,30.954091,5.620000,3.245000,69.590909,40.250000,94.648182,37.509091,9614.090909,24.704545,23.350000
Europe,17062.547170,18.039434,19.774906,1.661509,76.735849,10.050943,112.686981,48.458491,21272.641509,68.679245,68.826415
South-East Asia,167010.090909,29.056364,8.769091,2.560909,69.363636,35.045455,69.530000,32.627273,3470.000000,33.172727,33.454545
Western Pacific,68508.555556,28.664444,10.162963,2.067407,72.333333,24.711111,69.371481,30.040741,9067.037037,32.151852,32.166667

In [24]:
index_CM = means.ChildMortality.idxmin()
index_CM

'Europe'